
const FETCH_DATA_REQUEST = "FETCH_DATA_REQUEST";
const FETCH_DATA_SUCCESS = "FETCH_DATA_SUCCESS";
const FETCH_DATA_FAILURE = "FETCH_DATA_FAILURE";

const CREATE_POST_REQUEST = "CREATE_POST_REQUEST";
const CREATE_POST_SUCCESS = "CREATE_POST_SUCCESS";
const CREATE_POST_FAILURE = "CREATE_POST_FAILURE";

const UPDATE_POST = "UPDATE_POST";
const DELETE_POST = "DELETE_POST";
const LIKE_POST = "LIKE_POST";

export {
FETCH_DATA_REQUEST ,
 FETCH_DATA_SUCCESS,
 FETCH_DATA_FAILURE,
 CREATE_POST_REQUEST,
 CREATE_POST_SUCCESS,
 CREATE_POST_FAILURE,
 UPDATE_POST,
 DELETE_POST,
 LIKE_POST
};
